from django.conf.urls import url
from general import views

urlpatterns = [
	url(r'^$', views.blog, name='blog'),
	url(r'^todas-ofertas$', views.todas_ofertas, name='todas_ofertas'),
	url(r'^ofertas-internas$', views.blog_internas, name='blog_internas'),
	
	url(r'^departamento/(?P<codigo>\d+)/$', views.filtro_depto, name='filtro_depto'),
	url(r'^aplicar-oferta/(?P<codigo>\d+)/$', views.aplicar_oferta, name='aplicar_oferta'),
	url(r'^registro$', views.registro, name='registro'),
	url(r'^mensaje/(?P<mensaje>\d+)/$', views.mensaje_page, name='mensaje_page'),
	url(r'^login/$', views.login, name='login'),
	url(r'^accounts/login/$', views.login, name='login'),
	url(r'^logout/$', views.cerrar_sesion, name='cerrar_sesion'),
	url(r'^cargarmunicipios/$', views.cargar_municipios, name='cargar_municipios'),
	url(r'^registro/dos/$', views.registro_dos, name='registro_dos'),
	url(r'^activarusuario/(?P<id>\d+)/$', views.activar_usuario, name='activar_usuario'),
	url(r'^perfil$', views.perfil, name='perfil'),
	url(r'^datos/personales$', views.datos_generales, name='datos_personales'),
	url(r'^informacion/familiar$', views.informacion_familiar, name='informacion_familiar'),
	url(r'^informacion/economica$', views.informacion_economica, name='informacion_economica'),
	url(r'^informacion/laboral$', views.informacion_laboral, name='informacion_laboral'),
	url(r'^informacion/academica$', views.informacion_academica	, name='informacion_academica'),
	url(r'^informacion/referencias$', views.referencias	, name='referencias'),
	url(r'^ediciondatosgenerales/(?P<codigo>\d+)/$', views.editar_datosgenerales, name='editar_datosgenerales'),
	url(r'^editarcuenta/(?P<codigo>\d+)/$', views.editar_cuenta, name='editar_cuenta'),
	url(r'^eliminarcuenta/(?P<codigo>\d+)/$', views.eliminar_cuenta, name='eliminar_cuenta'),
	url(r'^nuevacuenta/(?P<solicitud>\d+)/$', views.nueva_cuenta, name='nueva_cuenta'),
	url(r'^editarvivienda/(?P<solicitud>\d+)/$', views.editar_vivienda, name='editar_vivienda'),
	url(r'^editardeuda/(?P<solicitud>\d+)/$', views.editar_deuda, name='editar_deuda'),
	url(r'^editarembargo/(?P<solicitud>\d+)/$', views.editar_embargo, name='editar_embargo'),
	url(r'^editarotrainformacion/(?P<solicitud>\d+)/$', views.editar_otrainformacion, name='editar_otrainformacion'),
	url(r'^editaraspiracionlaboral/(?P<solicitud>\d+)/$', views.editar_aspiracionlaboral, name='editar_aspiracionlaboral'),
	url(r'^editarhermano/(?P<codigo>\d+)/$', views.editar_hermanos, name='editar_hermanos'),
	url(r'^createhermano/(?P<codigo>\d+)/$', views.create_hermanos, name='create_hermanos'),
	url(r'^editarhijo/(?P<codigo>\d+)/$', views.editar_hijo, name='editar_hijo'),
	url(r'^createhijo/(?P<codigo>\d+)/$', views.create_hijo, name='create_hijo'),
	url(r'^createdependiente/(?P<codigo>\d+)/$', views.create_dependiente, name='create_dependiente'),
	url(r'^updatedependiente/(?P<codigo>\d+)/$', views.update_dependiente, name='update_dependiente'),
	url(r'^updatepadre/(?P<codigo>\d+)/$', views.update_padre, name='update_padre'),
	url(r'^updatemadre/(?P<codigo>\d+)/$', views.update_madre, name='update_madre'),
	url(r'^updateconyugue/(?P<codigo>\d+)/$', views.update_conyugue, name='update_conyugue'),
	url(r'^deletehermano/(?P<codigo>\d+)/$', views.delete_hermano, name='delete_hermano'),
	url(r'^deletehijo/(?P<codigo>\d+)/$', views.delete_hijo, name='delete_hijo'),
	url(r'^deletedependiente/(?P<codigo>\d+)/$', views.delete_dependiente, name='delete_dependiente'),
	url(r'^createlaboral/$', views.create_laboral, name='create_laboral'),

	url(r'^updatelaboral/(?P<codigo>\d+)/$', views.update_laboral, name='update_laboral'),
	url(r'^deletelaboral/(?P<codigo>\d+)/$', views.delete_laboral, name='delete_laboral'),

##################################### Referencias Personales ####################################################
	url(r'^create-referencia-personal/$', views.create_referencia_personal, name='create_referencia_personal'),
	url(r'^update-referencia-personal/(?P<codigo>\d+)/$', views.update_referencia_personal, name='update_referencia_personal'),
	url(r'^delete-referencia-personal/(?P<codigo>\d+)/$', views.delete_referencia_personal, name='delete_referencia_personal'),

#################################### Referencias Laborales
	url(r'^create-referencia-laboral/$', views.create_referencia_laboral, name='create_referencia_laboral'),
	url(r'^update-referencia-laboral/(?P<codigo>\d+)/$', views.update_referencia_laboral, name='update_referencia_laboral'),
	url(r'^delete-referencia-laboral/(?P<codigo>\d+)/$', views.delete_referencia_laboral, name='delete_referencia_laboral'),
	url(r'^editar_curso/(?P<codigo>\d+)/$', views.editar_curso, name='editar_curso'),
	url(r'^configuracion/$', views.configuracion, name='configuracion'),
	url(r'^cambiarimagen/$', views.cambiar_imagen, name='cambiar_imagen'),
	url(r'^editarinfoperfil/$', views.editar_infoperfil, name='editar_infoperfil'),
	url(r'^cambiarclave/$', views.cambiar_clave, name='cambiar_clave'),
	url(r'^nuevocurso/$', views.nuevo_curso, name='nuevo_curso'),
	url(r'^nuevoestudio/$', views.nuevo_estudio, name='nuevo_estudio'),
###################################### Habilidades #######################################################
	url(r'^create-habilidades/$', views.create_habilidades, name='create_habilidades'),
	url(r'^update-habilidades/(?P<codigo>\d+)/$', views.update_habilidades, name='update_habilidades'),
	url(r'^delete-habilidades/(?P<codigo>\d+)/$', views.delete_habilidades, name='delete_habilidades'),
	url(r'^editarestudio/(?P<codigo>\d+)/$', views.editar_estudio, name='editar_estudio'),
	url(r'^eliminarcompetencia/(?P<codigo>\d+)/$', views.eliminar_competencia, name='eliminar_competencia'),
	url(r'^agregarcompetencias/$', views.agregar_competencias, name='agregar_competencias'),
###################################### IDIOMA #######################################################
	url(r'^create-idioma/$', views.create_idioma, name='create_idioma'),
	url(r'^update-idioma/(?P<codigo>\d+)/$', views.update_idioma, name='update_idioma'),
	url(r'^delete-idioma/(?P<codigo>\d+)/$', views.delete_idioma, name='delete_idioma'),
	url(r'^recuperarclave/$', views.recuperar_clave, name='recuperar_clave'),

	url(r'^CV/$', views.cambiar_cv, name='cambiar_cv'),
	url(r'^suscribirse/$', views.suscribirse, name='suscribirse'),

]
