# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_departamento', models.AutoField(db_column='CodDepartamento', primary_key=True, serialize=False)),
                ('descripcion_departamento', models.CharField(blank=True, db_column='DescripcionDepartamento', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('cod_dependiente', models.AutoField(db_column='CodDependiente', primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('tipo_dependencia', models.CharField(blank=True, db_column='TipoDependencia', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Sol].[Dependientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('cod_hermano', models.AutoField(db_column='CodHermano', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('domicilio', models.CharField(blank=True, db_column='Domicilio', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=10, null=True)),
                ('ocupacion', models.CharField(blank=True, db_column='Ocupacion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Hermanos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('cod_hijo', models.AutoField(db_column='CodHijo', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
            ],
            options={
                'db_table': 'Sol].[Hijos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialacademico',
            fields=[
                ('cod_institucion', models.AutoField(db_column='CodInstitucion', primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(blank=True, db_column='NombreInstitucion', max_length=50, null=True)),
                ('estudios_realizados', models.CharField(blank=True, db_column='EstudiosRealizados', max_length=100, null=True)),
                ('lugar_estudio', models.CharField(blank=True, db_column='LugarEstudio', max_length=50, null=True)),
                ('fecha_estudio', models.DateField(blank=True, db_column='FechaEstudio', max_length=10, null=True)),
                ('titulo_obtenido', models.CharField(blank=True, db_column='TituloObtenido', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[HistorialAcademico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiallaboral',
            fields=[
                ('cod_empresa', models.AutoField(db_column='CodEmpresa', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, db_column='NombreEmpresa', max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='FechaINgreso', max_length=10, null=True)),
                ('fecha_egreso', models.DateField(blank=True, db_column='FechaEgreso', max_length=10, null=True)),
                ('direccion_empresa', models.CharField(blank=True, db_column='DireccionEmpresa', max_length=100, null=True)),
                ('nombre_jefe_inmediato', models.CharField(blank=True, db_column='NombreJefeInmediato', max_length=100, null=True)),
                ('motivo_retiro', models.CharField(blank=True, db_column='MotivoRetiro', max_length=100, null=True)),
                ('salario_inicial', models.DecimalField(blank=True, db_column='SalarioInicial', decimal_places=2, max_digits=18, null=True)),
                ('salario_final', models.DecimalField(blank=True, db_column='SalarioFinal', decimal_places=2, max_digits=18, null=True)),
                ('puesto', models.CharField(blank=True, db_column='Puesto', max_length=100, null=True)),
                ('fuciones_puesto', models.CharField(blank=True, db_column='FucionesPuesto', max_length=100, null=True)),
                ('horario', models.CharField(blank=True, db_column='Horario', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[HistorialLaboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cod_municipio', models.AutoField(db_column='CodMunicipio', primary_key=True, serialize=False)),
                ('descripcion_municipio', models.CharField(blank=True, db_column='DescripcionMunicipio', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('cod_organizacion', models.AutoField(db_column='CodOrganizacion', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'Sol].[Organizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cod_pais', models.AutoField(db_column='CodPais', primary_key=True, serialize=False)),
                ('descripcion_pais', models.CharField(blank=True, db_column='DescripcionPais', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Paises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('cod_referencia', models.AutoField(db_column='CodReferencia', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, db_column='Profesion', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=10, null=True)),
                ('tipo_referencia', models.CharField(blank=True, db_column='TipoReferencia', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Sol].[Referencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('cod_solicitud', models.AutoField(db_column='CodSolicitud', primary_key=True, serialize=False)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('vista', models.IntegerField(blank=True, db_column='Vista', null=True)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, db_column='PrimerApellido', max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, db_column='SegundoApellido', max_length=100, null=True)),
                ('apellido_casada', models.CharField(blank=True, db_column='ApellidoCasada', max_length=100, null=True)),
                ('direccion_domicilio', models.CharField(blank=True, db_column='DireccionDomicilio', max_length=200, null=True)),
                ('telefono_fijo', models.CharField(blank=True, db_column='TelefonoFijo', max_length=10, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=10, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, db_column='LugarNacimiento', max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='FechaNacimiento', max_length=10, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('estado_civil', models.CharField(blank=True, db_column='EstadoCivil', max_length=1, null=True)),
                ('profesion', models.CharField(blank=True, db_column='Profesion', max_length=1, null=True)),
                ('identidad', models.CharField(blank=True, db_column='Identidad', max_length=13, null=True)),
                ('automovil', models.NullBooleanField(db_column='Automovil')),
                ('licencia', models.NullBooleanField(db_column='Licencia')),
                ('tipo_licencia', models.CharField(blank=True, db_column='TipoLicencia', max_length=1, null=True)),
                ('poliza_seguro', models.NullBooleanField(db_column='PolizaSeguro')),
                ('compania_poliza', models.CharField(blank=True, db_column='CompaniaPoliza', max_length=100, null=True)),
                ('deporte', models.NullBooleanField(db_column='Deporte')),
                ('tipo_deporte', models.CharField(blank=True, db_column='TipoDeporte', max_length=100, null=True)),
                ('fecha_deporte', models.DateField(blank=True, db_column='FechaDeporte', max_length=10, null=True)),
                ('numero_ihss', models.CharField(blank=True, db_column='NumeroIhss', max_length=50, null=True)),
                ('rtn', models.CharField(blank=True, db_column='RTN', max_length=14, null=True)),
                ('numero_pasaporte', models.CharField(blank=True, db_column='NumeroPasaporte', max_length=50, null=True)),
                ('nombres_padre', models.CharField(blank=True, db_column='NombresPadre', max_length=100, null=True)),
                ('apellidos_padre', models.CharField(blank=True, db_column='ApellidosPadre', max_length=100, null=True)),
                ('edad_padre', models.IntegerField(blank=True, db_column='EdadPadre', null=True)),
                ('domicilio_padre', models.CharField(blank=True, db_column='DomicilioPadre', max_length=100, null=True)),
                ('telefono_padre', models.CharField(blank=True, db_column='TelefonoPadre', max_length=10, null=True)),
                ('profesion_padre', models.CharField(blank=True, db_column='ProfesionPadre', max_length=1, null=True)),
                ('direccion_laboral_padre', models.CharField(blank=True, db_column='DireccionLaboralPadre', max_length=200, null=True)),
                ('nombres_madre', models.CharField(blank=True, db_column='NombresMadre', max_length=100, null=True)),
                ('apellidos_madre', models.CharField(blank=True, db_column='ApellidosMadre', max_length=100, null=True)),
                ('edad_madre', models.IntegerField(blank=True, db_column='EdadMadre', null=True)),
                ('domicilio_madre', models.CharField(blank=True, db_column='DomicilioMadre', max_length=100, null=True)),
                ('telefono_madre', models.CharField(blank=True, db_column='TelefonoMadre', max_length=10, null=True)),
                ('profesion_madre', models.CharField(blank=True, db_column='ProfesionMadre', max_length=1, null=True)),
                ('direccion_laboral_madre', models.CharField(blank=True, db_column='DireccionLaboralMadre', max_length=200, null=True)),
                ('nombre_conyugue', models.CharField(blank=True, db_column='NombreConyugue', max_length=100, null=True)),
                ('edad_conyugue', models.IntegerField(blank=True, db_column='EdadConyugue', null=True)),
                ('domicilio_conyugue', models.CharField(blank=True, db_column='DomicilioConyugue', max_length=200, null=True)),
                ('telefono_conyugue', models.CharField(blank=True, db_column='TelefonoConyugue', max_length=10, null=True)),
                ('profesion_conyugue', models.CharField(blank=True, db_column='ProfesionConyugue', max_length=1, null=True)),
                ('direccion_laboral_conyugue', models.CharField(blank=True, db_column='DireccionLaboralConyugue', max_length=200, null=True)),
                ('tipo_vivienda', models.CharField(blank=True, db_column='TipoVivienda', max_length=50, null=True)),
                ('total_amortizacion', models.DecimalField(blank=True, db_column='TotalAmortizacion', decimal_places=2, max_digits=18, null=True)),
                ('total_inquilino', models.DecimalField(blank=True, db_column='TotalInquilino', decimal_places=2, max_digits=18, null=True)),
                ('total_pensionista', models.DecimalField(blank=True, db_column='TotalPensionista', decimal_places=2, max_digits=18, null=True)),
                ('cuentas_bancarias', models.NullBooleanField(db_column='CuentasBancarias')),
                ('institucion_cuenta', models.CharField(blank=True, db_column='InstitucionCuenta', max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, db_column='NumeroCuenta', max_length=50, null=True)),
                ('depositos_monetarios', models.NullBooleanField(db_column='DepositosMonetarios')),
                ('depositos_ahorros', models.NullBooleanField(db_column='DepositosAhorros')),
                ('otros_depositos', models.NullBooleanField(db_column='OtrosDepositos')),
                ('cantidad_depositos', models.DecimalField(blank=True, db_column='CantidadDepositos', decimal_places=2, max_digits=18, null=True)),
                ('deudas_pendientes', models.NullBooleanField(db_column='DeudasPendientes')),
                ('nombre_acreedor', models.CharField(blank=True, db_column='NombreAcreedor', max_length=100, null=True)),
                ('monto_deuda', models.DecimalField(blank=True, db_column='MontoDeuda', decimal_places=2, max_digits=18, null=True)),
                ('cuota_mensual', models.DecimalField(blank=True, db_column='CuotaMensual', decimal_places=2, max_digits=18, null=True)),
                ('embargado', models.NullBooleanField(db_column='Embargado')),
                ('nombre_quien_embargo', models.CharField(blank=True, db_column='NombreQuienEmbargo', max_length=100, null=True)),
                ('motivo_embargo', models.CharField(blank=True, db_column='MotivoEmbargo', max_length=200, null=True)),
                ('monto_embargo', models.DecimalField(blank=True, db_column='MontoEmbargo', decimal_places=2, max_digits=18, null=True)),
                ('valores_efectivo', models.NullBooleanField(db_column='ValoresEfectivo')),
                ('monto_efectivo', models.DecimalField(blank=True, db_column='MontoEfectivo', decimal_places=2, max_digits=18, null=True)),
                ('familiares_institucion', models.NullBooleanField(db_column='FamiliaresInstitucion')),
                ('nombre_familiar', models.CharField(blank=True, db_column='NombreFamiliar', max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, db_column='Parentesco', max_length=1, null=True)),
                ('puesto_familiar', models.CharField(blank=True, db_column='PuestoFamiliar', max_length=50, null=True)),
                ('trabajar_cualquier_lugar', models.NullBooleanField(db_column='TrabajarCualquierLugar')),
                ('nombre_quien_recomienda', models.CharField(blank=True, db_column='NombreQuienRecomienda', max_length=100, null=True)),
                ('puesto_que_solicita', models.CharField(blank=True, db_column='PuestoQueSolicita', max_length=100, null=True)),
                ('sueldo_pretende', models.DecimalField(blank=True, db_column='SueldoPretende', decimal_places=2, max_digits=18, null=True)),
                ('fecha_inicio', models.DateField(blank=True, db_column='FechaInicio', max_length=10, null=True)),
                ('otro_idioma', models.NullBooleanField(db_column='OtroIdioma')),
                ('nombre_idioma', models.CharField(blank=True, db_column='NombreIdioma', max_length=50, null=True)),
                ('habla_idioma', models.CharField(blank=True, db_column='HablaIdioma', max_length=10, null=True)),
                ('escribe_idioma', models.CharField(blank=True, db_column='EscribeIdioma', max_length=10, null=True)),
                ('lee_idioma', models.CharField(blank=True, db_column='LeeIdioma', max_length=10, null=True)),
                ('enfermedades_ha_padecido', models.CharField(blank=True, db_column='EnfermedadesHaPadecido', max_length=200, null=True)),
                ('consume_medicamentos', models.NullBooleanField(db_column='ConsumeMedicamentos')),
                ('impedimentos_fisicos', models.NullBooleanField(db_column='ImpedimentosFisicos')),
                ('observaciones_adicionales', models.CharField(blank=True, db_column='ObservacionesAdicionales', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sol].[Solicitudes',
                'managed': False,
            },
        ),
    ]
