# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('cod_campus', models.AutoField(db_column='Cod_campus', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('cod_carreras', models.AutoField(db_column='Cod_carreras', primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(blank=True, db_column='Nombre_carrera', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sol].[Carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarrerasSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_universidad', models.IntegerField(db_column='Cod_universidad')),
                ('cod_campus', models.IntegerField(db_column='Cod_campus')),
            ],
            options={
                'db_table': 'Sol].[Carreras_Solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('cod_colegios', models.AutoField(db_column='Cod_Colegios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=300, null=True)),
            ],
            options={
                'db_table': 'Sol].[Colegios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('cod_compentencias', models.AutoField(db_column='Cod_compentencias', primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(blank=True, db_column='Nombre_competencia', max_length=50, null=True)),
                ('posee', models.NullBooleanField(db_column='Posee')),
            ],
            options={
                'db_table': 'Sol].[Competencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('cod_cuenta', models.AutoField(db_column='Cod_cuenta', primary_key=True, serialize=False)),
                ('tipo_cuenta', models.CharField(blank=True, db_column='Tipo_cuenta', max_length=1, null=True)),
                ('cantidad', models.DecimalField(blank=True, db_column='Cantidad', decimal_places=2, max_digits=18, null=True)),
                ('institucion', models.CharField(blank=True, db_column='Institucion', max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, db_column='Numero_cuenta', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('codcurso', models.AutoField(db_column='CodCurso', primary_key=True, serialize=False)),
                ('temacurso', models.CharField(blank=True, db_column='TemaCurso', max_length=100, null=True)),
                ('nombrecentroestudio', models.CharField(blank=True, db_column='NombreCentroEstudio', max_length=100, null=True)),
                ('direccioncentroestudio', models.CharField(blank=True, db_column='DireccionCentroEstudio', max_length=150, null=True)),
                ('duracion', models.CharField(blank=True, db_column='Duracion', max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('coddepartamento', models.AutoField(db_column='CodDepartamento', primary_key=True, serialize=False)),
                ('descripciondepartamento', models.CharField(blank=True, db_column='DescripcionDepartamento', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependientes',
            fields=[
                ('coddependiente', models.AutoField(db_column='CodDependiente', primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('tipodependencia', models.CharField(blank=True, db_column='TipoDependencia', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Sol].[Dependientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('cod_escuelas', models.IntegerField(db_column='Cod_escuelas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=300, null=True)),
            ],
            options={
                'db_table': 'Sol].[Escuelas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('cod_habilidad', models.AutoField(db_column='Cod_habilidad', primary_key=True, serialize=False)),
                ('nombre_habilidad', models.CharField(blank=True, db_column='Nombre_habilidad', max_length=50, null=True)),
                ('porcentaje', models.IntegerField(blank=True, db_column='Porcentaje', null=True)),
            ],
            options={
                'db_table': 'Sol].[Habilidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hermanos',
            fields=[
                ('codhermano', models.AutoField(db_column='CodHermano', primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('domicilio', models.CharField(blank=True, db_column='Domicilio', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=10, null=True)),
                ('ocupacion', models.CharField(blank=True, db_column='Ocupacion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Hermanos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hijos',
            fields=[
                ('codhijo', models.AutoField(db_column='CodHijo', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
            ],
            options={
                'db_table': 'Sol].[Hijos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('cod_idioma', models.AutoField(db_column='Cod_idioma', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('habla', models.IntegerField(blank=True, db_column='Habla', null=True)),
                ('escritura', models.IntegerField(blank=True, db_column='Escritura', null=True)),
                ('lectura', models.IntegerField(blank=True, db_column='Lectura', null=True)),
            ],
            options={
                'db_table': 'Sol].[Idiomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('codmunicipio', models.AutoField(db_column='CodMunicipio', primary_key=True, serialize=False)),
                ('descripcionmunicipio', models.CharField(blank=True, db_column='DescripcionMunicipio', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organiacion',
            fields=[
                ('cod_organizacion', models.AutoField(db_column='Cod_organizaciones', primary_key=True, serialize=False)),
                ('nombre_organizacion', models.CharField(blank=True, db_column='Nombre_organizacion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sol].[Grupo_organiacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('codpais', models.AutoField(db_column='CodPais', primary_key=True, serialize=False)),
                ('descripcionpais', models.CharField(blank=True, db_column='DescripcionPais', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sol].[Paises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('codreferencia', models.AutoField(db_column='CodReferencia', primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, db_column='Profesion', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=10, null=True)),
                ('tiporeferencia', models.CharField(blank=True, db_column='TipoReferencia', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Sol].[Referencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referenciaspersonales',
            fields=[
                ('codreferenciapersonal', models.AutoField(db_column='CodReferenciaPersonal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, db_column='Profesion', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Sol].[ReferenciasPersonales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('codsolicitud', models.AutoField(db_column='CodSolicitud', primary_key=True, serialize=False)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('vista', models.IntegerField(blank=True, db_column='Vista', null=True)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=100, null=True)),
                ('primerapellido', models.CharField(blank=True, db_column='PrimerApellido', max_length=100, null=True)),
                ('segundoapellido', models.CharField(blank=True, db_column='SegundoApellido', max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=10, null=True)),
                ('casada', models.NullBooleanField(db_column='Casada')),
                ('apellidocasada', models.CharField(blank=True, db_column='ApellidoCasada', max_length=100, null=True)),
                ('direcciondomicilio', models.CharField(blank=True, db_column='DireccionDomicilio', max_length=200, null=True)),
                ('telefonofijo', models.CharField(blank=True, db_column='TelefonoFijo', max_length=10, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=10, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, db_column='LugarNacimiento', max_length=100, null=True)),
                ('fechanacimiento', models.CharField(blank=True, db_column='FechaNacimiento', max_length=10, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('estadocivil', models.CharField(blank=True, db_column='EstadoCivil', max_length=1, null=True)),
                ('profesion', models.CharField(blank=True, db_column='Profesion', max_length=1, null=True)),
                ('identidad', models.CharField(blank=True, db_column='Identidad', max_length=13, null=True)),
                ('automovil', models.NullBooleanField(db_column='Automovil')),
                ('licencia', models.NullBooleanField(db_column='Licencia')),
                ('tipolicencia', models.CharField(blank=True, db_column='TipoLicencia', max_length=1, null=True)),
                ('polizaseguro', models.NullBooleanField(db_column='PolizaSeguro')),
                ('companiapoliza', models.CharField(blank=True, db_column='CompaniaPoliza', max_length=100, null=True)),
                ('deporte', models.NullBooleanField(db_column='Deporte')),
                ('tipodeporte', models.CharField(blank=True, db_column='TipoDeporte', max_length=100, null=True)),
                ('fechadeporte', models.CharField(blank=True, db_column='FechaDeporte', max_length=10, null=True)),
                ('numeroihss', models.CharField(blank=True, db_column='NumeroIhss', max_length=50, null=True)),
                ('rtn', models.CharField(blank=True, db_column='RTN', max_length=14, null=True)),
                ('numeropasaporte', models.CharField(blank=True, db_column='NumeroPasaporte', max_length=50, null=True)),
                ('organizaciones', models.CharField(blank=True, db_column='Organizaciones', max_length=250, null=True)),
                ('nombrespadre', models.CharField(blank=True, db_column='NombresPadre', max_length=100, null=True)),
                ('apellidospadre', models.CharField(blank=True, db_column='ApellidosPadre', max_length=100, null=True)),
                ('edadpadre', models.IntegerField(blank=True, db_column='EdadPadre', null=True)),
                ('domiciliopadre', models.CharField(blank=True, db_column='DomicilioPadre', max_length=100, null=True)),
                ('telefonopadre', models.CharField(blank=True, db_column='TelefonoPadre', max_length=10, null=True)),
                ('profesionpadre', models.CharField(blank=True, db_column='ProfesionPadre', max_length=1, null=True)),
                ('direccionlaboralpadre', models.CharField(blank=True, db_column='DireccionLaboralPadre', max_length=200, null=True)),
                ('nombresmadre', models.CharField(blank=True, db_column='NombresMadre', max_length=100, null=True)),
                ('apellidosmadre', models.CharField(blank=True, db_column='ApellidosMadre', max_length=100, null=True)),
                ('edadmadre', models.IntegerField(blank=True, db_column='EdadMadre', null=True)),
                ('domiciliomadre', models.CharField(blank=True, db_column='DomicilioMadre', max_length=100, null=True)),
                ('telefonomadre', models.CharField(blank=True, db_column='TelefonoMadre', max_length=10, null=True)),
                ('profesionmadre', models.CharField(blank=True, db_column='ProfesionMadre', max_length=1, null=True)),
                ('direccionlaboralmadre', models.CharField(blank=True, db_column='DireccionLaboralMadre', max_length=200, null=True)),
                ('hermanos', models.NullBooleanField(db_column='Hermanos')),
                ('cantidadhermanos', models.IntegerField(blank=True, db_column='CantidadHermanos', null=True)),
                ('cantidadhijos', models.IntegerField(blank=True, db_column='CantidadHijos', null=True)),
                ('cantidaddependientes', models.IntegerField(blank=True, db_column='CantidadDependientes', null=True)),
                ('nombreconyugue', models.CharField(blank=True, db_column='NombreConyugue', max_length=100, null=True)),
                ('edadconyugue', models.IntegerField(blank=True, db_column='EdadConyugue', null=True)),
                ('domicilioconyugue', models.CharField(blank=True, db_column='DomicilioConyugue', max_length=200, null=True)),
                ('telefonoconyugue', models.CharField(blank=True, db_column='TelefonoConyugue', max_length=10, null=True)),
                ('profesionconyugue', models.CharField(blank=True, db_column='ProfesionConyugue', max_length=1, null=True)),
                ('direccionlaboralconyugue', models.CharField(blank=True, db_column='DireccionLaboralConyugue', max_length=200, null=True)),
                ('tipovivienda', models.CharField(blank=True, db_column='TipoVivienda', max_length=50, null=True)),
                ('totalamortizacion', models.DecimalField(blank=True, db_column='TotalAmortizacion', decimal_places=2, max_digits=18, null=True)),
                ('totalinquilino', models.DecimalField(blank=True, db_column='TotalInquilino', decimal_places=2, max_digits=18, null=True)),
                ('totalpensionista', models.DecimalField(blank=True, db_column='TotalPensionista', decimal_places=2, max_digits=18, null=True)),
                ('deudaspendientes', models.DecimalField(blank=True, db_column='DeudasPendientes', decimal_places=2, max_digits=18, null=True)),
                ('nombreacreedor', models.CharField(blank=True, db_column='NombreAcreedor', max_length=100, null=True)),
                ('montodeuda', models.DecimalField(blank=True, db_column='MontoDeuda', decimal_places=2, max_digits=18, null=True)),
                ('cuotamensual', models.DecimalField(blank=True, db_column='CuotaMensual', decimal_places=2, max_digits=18, null=True)),
                ('embargado', models.NullBooleanField(db_column='Embargado')),
                ('nombrequienembargo', models.CharField(blank=True, db_column='NombreQuienEmbargo', max_length=100, null=True)),
                ('motivoembargo', models.CharField(blank=True, db_column='MotivoEmbargo', max_length=200, null=True)),
                ('montoembargo', models.DecimalField(blank=True, db_column='MontoEmbargo', decimal_places=2, max_digits=18, null=True)),
                ('valoresefectivo', models.NullBooleanField(db_column='ValoresEfectivo')),
                ('montoefectivo', models.DecimalField(blank=True, db_column='MontoEfectivo', decimal_places=2, max_digits=18, null=True)),
                ('familiaresinstitucion', models.NullBooleanField(db_column='FamiliaresInstitucion')),
                ('nombrefamiliar', models.CharField(blank=True, db_column='NombreFamiliar', max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, db_column='Parentesco', max_length=1, null=True)),
                ('puestofamiliar', models.CharField(blank=True, db_column='PuestoFamiliar', max_length=50, null=True)),
                ('trabajarcualquierlugar', models.NullBooleanField(db_column='TrabajarCualquierLugar')),
                ('nombrequienrecomienda', models.CharField(blank=True, db_column='NombreQuienRecomienda', max_length=100, null=True)),
                ('puestoquesolicita', models.CharField(blank=True, db_column='PuestoQueSolicita', max_length=100, null=True)),
                ('sueldopretende', models.DecimalField(blank=True, db_column='SueldoPretende', decimal_places=2, max_digits=18, null=True)),
                ('fechainicio', models.CharField(blank=True, db_column='FechaInicio', max_length=10, null=True)),
                ('enfermedadeshapadecido', models.CharField(blank=True, db_column='EnfermedadesHaPadecido', max_length=200, null=True)),
                ('consumemedicamentos', models.NullBooleanField(db_column='ConsumeMedicamentos')),
                ('impedimentosfisicos', models.NullBooleanField(db_column='ImpedimentosFisicos')),
                ('observacionesadicionales', models.CharField(blank=True, db_column='ObservacionesAdicionales', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sol].[Solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('cod_univesidad', models.IntegerField(db_column='Cod_univesidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Universidades',
                'managed': False,
            },
        ),
    ]
